### ISSUE TITLE
Todo #1

### ISSUE THREAD

**Issue by michael-255** [michael-255/vue3-boilerplate-app-v2#1]
- [x] Proof read **Settings** card text
- [x] Proof read **Dashboard** card text
- [x] Add option to switch between light/dark mode theme
- [x] Make sure info logs are always displayed
- [ ] Rename some card list components as ***Container**
- [ ] Implement an Active route for a simple activity timer (will be expanded on in another app)
- [ ] (maybe) Organize composables (use) in components directory (with tests)?
- [ ] (maybe) Reusable composables in components/shared/use?
- [ ] (maybe) Split script code off of template code for use in the composables (easier to test)?
